import { beforeEach, describe, expect, it } from "vitest";
import { createTestHarness } from "@paperclipai/plugin-sdk/testing";
import manifest from "../src/manifest.js";
import plugin from "../src/worker.js";
import { ACTION_KEYS } from "../src/constants.js";
import { createDnaReport, reanalyzeDnaReport } from "../src/dna.js";

const dnaSample23AndMe = `# This data file generated by 23andMe at: Mon Jan 15 12:34:56 2024
#
rsid\tchromosome\tposition\tgenotype
rs1801133\t1\t11856378\tTT
rs1801131\t1\t11854476\tGG
rs1805087\t1\t236885200\tGG
rs1815739\t11\t66560624\tCT
rs429358\t19\t44908684\tCT
rs4680\t22\t19963748\tAA
rs762551\t15\t75011234\tCC
rs2298383\t22\t24763011\tTT
rs4244285\t10\t94761942\tGA
rs4149056\t12\t21178615\tCC
rs2187668\t6\t32609137\tCT
rs1800562\t6\t26091179\tGA
rs17580\t14\t94844947\tAT
rs2802292\t6\t108998794\tGG
rs8176719\t9\t136132908\tDI
rs8176746\t9\t136132911\tGG
rs505922\t9\t136149229\tCT
rs713598\t7\t141673345\tCT
rs1726866\t7\t141673586\tCT
rs10246939\t7\t141673733\tCT
rs2651899\t1\t145345634\tTT
rs1006737\t12\t22804737\tAA
rs12913832\t15\t28365618\tAG
rs1805007\t16\t89986117\tCT
rs4880\t6\t160113872\tGG
rs1695\t11\t67585218\tGG
`;

const sampleBloodworkPanels = [
  {
    name: "Cardiometabolic",
    biomarkers: [
      { name: "Albumin", value: 4.1, unit: "g/dL" },
      { name: "Creatinine", value: 1.05, unit: "mg/dL" },
      { name: "Glucose", value: 102, unit: "mg/dL" },
      { name: "High-sensitivity C-reactive protein", value: 2.4, unit: "mg/L" },
      { name: "LDL cholesterol", value: 132, unit: "mg/dL" },
      { name: "HDL cholesterol", value: 43, unit: "mg/dL" },
      { name: "Total cholesterol", value: 214, unit: "mg/dL" },
      { name: "Triglycerides", value: 168, unit: "mg/dL" },
      { name: "Hemoglobin A1c", value: 5.8, unit: "%" },
    ],
  },
  {
    name: "CBC / Recovery",
    biomarkers: [
      { name: "Lymphocyte %", value: 24, unit: "%" },
      { name: "MCV", value: 92, unit: "fL" },
      { name: "RDW", value: 13.8, unit: "%" },
      { name: "Alkaline phosphatase", value: 88, unit: "U/L" },
      { name: "Blood urea nitrogen", value: 19, unit: "mg/dL" },
      { name: "Vitamin D (25-hydroxyvitamin D)", value: 26, unit: "ng/mL" },
      { name: "Magnesium", value: 1.8, unit: "mg/dL" },
      { name: "Ferritin", value: 42, unit: "ng/mL" },
      { name: "Free testosterone", value: 72, unit: "pg/mL" },
      { name: "Sex-hormone binding globulin", value: 48, unit: "nmol/L" },
    ],
  },
];

const sampleLabImportCsv = `panel,name,value,unit,low,high
Cardiometabolic,Glucose,5.6,mmol/L,3.9,5.5
Cardiometabolic,LDL cholesterol,3.4,mmol/L,0,3.0
Recovery,Ferritin,55,ug/L,20,300
`;

const dnaSampleVcf = `##fileformat=VCFv4.2
##reference=GRCh38
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE
1\t11856378\trs1801133\tC\tT\t.\tPASS\t.\tGT\t1/1
19\t44908684\trs429358\tT\tC\t.\tPASS\t.\tGT\t0/1
15\t75011234\trs762551\tA\tC\t.\tPASS\t.\tGT\t1/1
`;

const dnaSampleDelimited = `rsid\tchromosome\tposition\tresult
rs1801133\t1\t11856378\tTT
rs429358\t19\t44908684\tCT
`;

const dnaSample23AndMeCsv = `rsid,chromosome,position,genotype
rs1801133,1,11856378,TT
rs429358,19,44908684,CT
`;

describe("Personal Health plugin", () => {
  let harness: Awaited<ReturnType<typeof buildHarness>>;

  beforeEach(async () => {
    harness = await buildHarness();
  });

  it("exposes the expected manifest", () => {
    expect(manifest.id).toBe("personal-health");
    expect(manifest.capabilities).toContain("activity.log.write");
  });

  it("plans and summarizes workouts", async () => {
    const { workoutPlan } = await harness.performAction(ACTION_KEYS.ADD_WORKOUT_PLAN, {
      name: "Strength Base",
      type: "strength",
      phase: "build",
      targetDurationMinutes: 60,
      targetDaysPerWeek: 3,
    }) as { workoutPlan: { id: string } };

    await harness.performAction(ACTION_KEYS.LOG_WORKOUT, {
      name: "Upper body",
      type: "strength",
      durationMinutes: 65,
      rpe: 8,
      caloriesBurned: 420,
      performedAt: "2026-04-17T08:00:00Z",
    });

    const summary = await harness.performAction(ACTION_KEYS.GET_WORKOUT_SUMMARY, { days: 7 }) as { totalSessions: number; totalDurationMinutes: number };
    expect(summary.totalSessions).toBe(1);
    expect(summary.totalDurationMinutes).toBe(65);

    const plan = await harness.performAction(ACTION_KEYS.PLAN_WEEKLY_WORKOUTS, {
      availableHours: 5,
      weekStart: "2026-04-20",
      phase: "build",
    }) as { sessions: Array<{ workoutPlanId: string }> };
    expect(plan.sessions.length).toBeGreaterThan(0);
    expect(plan.sessions[0].workoutPlanId).toBe(workoutPlan.id);
  });

  it("tracks nutrition and hydration targets", async () => {
    await harness.performAction(ACTION_KEYS.SET_CALORIE_TARGET, { calories: 2400 });
    await harness.performAction(ACTION_KEYS.SET_HYDRATION_GOAL, { goalMl: 3000 });
    await harness.performAction(ACTION_KEYS.LOG_MEAL, {
      date: "2026-04-18",
      mealName: "breakfast",
      foods: [
        { name: "Greek yogurt", calories: 140, proteinGrams: 16, carbGrams: 6, fatGrams: 4 },
        { name: "Blueberries", calories: 84, proteinGrams: 1, carbGrams: 21, fatGrams: 0, fiberGrams: 4 },
      ],
    });
    await harness.performAction(ACTION_KEYS.LOG_HYDRATION, {
      date: "2026-04-18",
      amountMl: 750,
    });

    const nutrition = await harness.performAction(ACTION_KEYS.GET_NUTRITION_SUMMARY, {
      startDate: "2026-04-18",
      endDate: "2026-04-18",
    }) as { totalCalories: number; calorieTarget: number; totalMacros: { proteinGrams: number } };
    expect(nutrition.totalCalories).toBe(224);
    expect(nutrition.calorieTarget).toBe(2400);
    expect(nutrition.totalMacros.proteinGrams).toBe(17);

    const hydration = await harness.performAction(ACTION_KEYS.GET_HYDRATION, { date: "2026-04-18" }) as { totalMl: number; goalMl: number };
    expect(hydration.totalMl).toBe(750);
    expect(hydration.goalMl).toBe(3000);

    const foodDetail = await harness.performAction(ACTION_KEYS.GET_FOOD_DETAILS, { id: "food-greek-yogurt" }) as { food: { name: string } };
    expect(foodDetail.food.name).toBe("Greek yogurt");
  });

  it("parses raw DNA data into actionable reports and exports markdown", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string; healthInsights: Array<{ title: string }> } };

    expect(added.dnaReport.healthInsights.length).toBeGreaterThan(0);

    const reportId = added.dnaReport.id;
    const detail = await harness.performAction(ACTION_KEYS.GET_DNA_VARIANT_DETAIL, {
      reportId,
      rsId: "rs1801133",
    }) as { detail: { variant: { genotype: string } } };
    expect(detail.detail.variant.genotype).toBe("TT");

    const lookup = await harness.performAction(ACTION_KEYS.LOOKUP_RSID, { rsId: "rs429358" }) as { matches: Array<unknown> };
    expect(lookup.matches.length).toBe(1);

    const exported = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, { reportId }) as { markdown: string };
    expect(exported.markdown).toContain("Actionable Health Protocol");
    expect(exported.markdown).toContain("MTHFR");
    expect(exported.markdown).toContain("Disease Risk Watchlist");
    expect(exported.markdown).toContain("Pharmacogenomic Watch-outs");
    expect(exported.markdown).toContain("Trait Snapshots");
    expect(exported.markdown).toContain("Carrier / Protective Notes");

    const priority = await harness.performAction(ACTION_KEYS.GET_DNA_PRIORITY_FINDINGS, { reportId }) as { priorityFindings: Array<{ title: string }> };
    expect(priority.priorityFindings[0].title.length).toBeGreaterThan(0);

    const diseaseRisks = await harness.performAction(ACTION_KEYS.GET_DNA_DISEASE_RISKS, { reportId }) as { diseaseRisks: Array<{ domain: string }> };
    expect(diseaseRisks.diseaseRisks.length).toBeGreaterThan(0);

    const pharmacogenomics = await harness.performAction(ACTION_KEYS.GET_DNA_PHARMACOGENOMICS, { reportId }) as { pharmacogenomics: Array<{ gene: string }> };
    expect(pharmacogenomics.pharmacogenomics.length).toBeGreaterThan(0);

    const pathways = await harness.performAction(ACTION_KEYS.GET_DNA_PATHWAYS, { reportId }) as { pathways: Array<{ pathway: string }> };
    expect(pathways.pathways.length).toBeGreaterThan(0);

    const traits = await harness.performAction(ACTION_KEYS.GET_DNA_TRAITS, { reportId }) as { traits: Array<{ title: string }> };
    expect(traits.traits.length).toBeGreaterThan(0);
    expect(traits.traits.some((entry) => entry.title.includes("Blood Type") || entry.title.includes("Caffeine") || entry.title.includes("Training"))).toBe(true);

    const carrierStatus = await harness.performAction(ACTION_KEYS.GET_DNA_CARRIER_STATUS, { reportId }) as { carrierStatus: Array<{ gene: string }> };
    expect(carrierStatus.carrierStatus.some((entry) => entry.gene === "HFE" || entry.gene === "SERPINA1")).toBe(true);

    const protective = await harness.performAction(ACTION_KEYS.GET_DNA_PROTECTIVE_VARIANTS, { reportId }) as { protectiveVariants: Array<{ gene: string }> };
    expect(protective.protectiveVariants.some((entry) => entry.gene === "FOXO3" || entry.gene === "APOE")).toBe(true);

    const monitoring = await harness.performAction(ACTION_KEYS.GET_DNA_MONITORING_PLAN, { reportId }) as { monitoringPlan: Array<{ focus: string }> };
    expect(monitoring.monitoringPlan.length).toBeGreaterThan(0);

    const supplements = await harness.performAction(ACTION_KEYS.GET_DNA_SUPPLEMENT_RECOMMENDATIONS, { reportId }) as { supplementRecommendations: Array<{ supplement: string }> };
    expect(supplements.supplementRecommendations.some((entry) => entry.supplement.toLowerCase().includes("methylfolate") || entry.supplement.toLowerCase().includes("vitamin"))).toBe(true);

    const comprehensive = await harness.performAction(ACTION_KEYS.EXPORT_DNA_COMPREHENSIVE_REPORT, { reportId }) as { markdown: string };
    expect(comprehensive.markdown).toContain("Comprehensive Genetics Report");
    expect(comprehensive.markdown).toContain("Trait Summaries");
    expect(comprehensive.markdown).toContain("Carrier Status");
    expect(comprehensive.markdown).toContain("Supplement Considerations");
  });

  it("analyzes bloodwork against BloodWork-inspired biomarker logic and biological age", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-04-17T09:00:00Z",
      panels: sampleBloodworkPanels,
      notes: "fasted morning draw",
    }) as { labResult: { id: string } };

    const biomarkerLookup = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_BIOMARKER, {
      query: "vitamin d",
    }) as { biomarker: { id: string; category: string } };
    expect(biomarkerLookup.biomarker.id).toBe("vitamin-d");
    expect(biomarkerLookup.biomarker.category).toBe("Hormone Balance");

    const analysis = await harness.performAction(ACTION_KEYS.ANALYZE_BLOODWORK, {
      labResultId: added.labResult.id,
      age: 34,
      chronologicalAge: 34,
      sex: "male",
    }) as { success: boolean; analysis: { evaluatedBiomarkers: Array<{ status: string }>; overallSummary: string; coverageSummary: string } };
    expect(analysis.success).toBe(true);
    expect(analysis.analysis.evaluatedBiomarkers.length).toBeGreaterThan(8);
    expect(analysis.analysis.overallSummary).toContain("Strongest category");
    expect(analysis.analysis.coverageSummary).toContain("coverage");

    const categoryScores = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_CATEGORY_SCORES, {
      labResultId: added.labResult.id,
      age: 34,
      sex: "male",
    }) as { categoryScores: Array<{ category: string; score: number }> };
    expect(categoryScores.categoryScores.some((entry) => entry.category === "Heart Health")).toBe(true);

    const biologicalAge = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      labResultId: added.labResult.id,
      chronologicalAge: 34,
      sex: "male",
      clockMethod: "kdm-style-clinical-clock",
    }) as { biologicalAge: { method: string; status: string; comboSignals: Array<{ name: string }> } };
    expect(biologicalAge.biologicalAge.method).toBe("kdm-style-clinical-clock");
    expect(biologicalAge.biologicalAge.status).toBe("available");
    expect(biologicalAge.biologicalAge.comboSignals.some((entry) => entry.name === "Metabolic Combo")).toBe(true);

    const actionPlan = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_ACTION_PLAN, {
      labResultId: added.labResult.id,
      age: 34,
      sex: "male",
    }) as { actionPlan: Array<{ biomarkerName: string }> };
    expect(actionPlan.actionPlan.length).toBeGreaterThan(0);
  });

  it("enforces privacy mode, confirmation gates, and audit logging for DNA", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "private-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "privacy",
    }) as { dnaReport: { id: string; isPrivacyRestricted: boolean; variants: unknown[]; ancestryComposition?: unknown } };

    expect(added.dnaReport.isPrivacyRestricted).toBe(true);
    expect(added.dnaReport.variants).toHaveLength(0);
    expect(added.dnaReport.ancestryComposition).toBeUndefined();

    const reportId = added.dnaReport.id;
    const variants = await harness.performAction(ACTION_KEYS.GET_DNA_VARIANTS, { reportId }) as { dnaVariants: unknown[]; error?: string };
    expect(variants.dnaVariants).toHaveLength(0);
    expect(variants.error).toContain("explicit confirmation");

    const aggregateInsights = await harness.performAction(ACTION_KEYS.GET_DNA_INSIGHTS, {}) as {
      dnaInsights: unknown[];
      warning?: string;
    };
    expect(aggregateInsights.dnaInsights).toHaveLength(0);
    expect(aggregateInsights.warning).toContain("omitted");

    const confirmedInsights = await harness.performAction(ACTION_KEYS.GET_DNA_INSIGHTS, {
      confirmSensitive: true,
    }) as { dnaInsights: unknown[] };
    expect(confirmedInsights.dnaInsights.length).toBeGreaterThan(0);

    const priority = await harness.performAction(ACTION_KEYS.GET_DNA_PRIORITY_FINDINGS, { reportId }) as {
      priorityFindings: unknown[];
      error?: string;
    };
    expect(priority.priorityFindings).toHaveLength(0);
    expect(priority.error).toContain("explicit confirmation");

    const confirmedPriority = await harness.performAction(ACTION_KEYS.GET_DNA_PRIORITY_FINDINGS, {
      reportId,
      confirmSensitive: true,
    }) as { priorityFindings: unknown[] };
    expect(Array.isArray(confirmedPriority.priorityFindings)).toBe(true);

    const exportAttempt = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
      reportId,
      includeSensitive: true,
      confirmSensitive: true,
    }) as { error?: string; markdown: string };
    expect(exportAttempt.error).toContain("Sensitive export disabled");

    const privacyStatus = await harness.performAction(ACTION_KEYS.GET_PRIVACY_STATUS, {}) as { summary: string };
    expect(privacyStatus.summary.toLowerCase()).toContain("privacy mode");

    const reports = await harness.performAction(ACTION_KEYS.GET_DNA_REPORTS, {}) as {
      dnaReports: Array<{ id: string; healthInsights: unknown[] }>;
      warning?: string;
    };
    const redactedReport = reports.dnaReports.find((entry) => entry.id === reportId);
    expect(redactedReport?.healthInsights).toEqual([]);
    expect(reports.warning).toContain("redacted");

    const compareBlocked = await harness.performAction(ACTION_KEYS.COMPARE_DNA_REPORTS, {
      leftReportId: reportId,
      rightReportId: reportId,
    }) as { success: boolean; error?: string };
    expect(compareBlocked.success).toBe(false);
    expect(compareBlocked.error).toContain("explicit confirmation");

    const compareConfirmed = await harness.performAction(ACTION_KEYS.COMPARE_DNA_REPORTS, {
      leftReportId: reportId,
      rightReportId: reportId,
      confirmSensitive: true,
    }) as { success: boolean; comparison: { changedVariants: unknown[] } };
    expect(compareConfirmed.success).toBe(true);
    expect(Array.isArray(compareConfirmed.comparison.changedVariants)).toBe(true);

    const lookupConfirmed = await harness.performAction(ACTION_KEYS.LOOKUP_RSID, {
      rsId: "rs1801133",
      confirmSensitive: true,
    }) as { matches: Array<{ reportId: string }> };
    expect(Array.isArray(lookupConfirmed.matches)).toBe(true);

    const annotateBlocked = await harness.performAction(ACTION_KEYS.ANNOTATE_VARIANT, {
      reportId,
      rsId: "rs1801133",
      note: "Private note",
    }) as { success: boolean; error?: string };
    expect(annotateBlocked.success).toBe(false);
    expect(annotateBlocked.error).toContain("explicit confirmation");

    const annotateConfirmed = await harness.performAction(ACTION_KEYS.ANNOTATE_VARIANT, {
      reportId,
      rsId: "rs1801133",
      note: "Private note",
      confirmSensitive: true,
    }) as { success: boolean };
    expect(annotateConfirmed.success).toBe(true);

    const auditLog = await harness.performAction(ACTION_KEYS.GET_HEALTH_AUDIT_LOG, {
      confirmSensitive: true,
    }) as { auditLog: Array<{ action: string }> };
    expect(auditLog.auditLog.some((entry) => entry.action === ACTION_KEYS.ADD_DNA_REPORT)).toBe(true);
    expect(auditLog.auditLog.some((entry) => entry.action === ACTION_KEYS.GET_HEALTH_AUDIT_LOG)).toBe(true);
    expect(auditLog.auditLog.some((entry) => entry.action === ACTION_KEYS.COMPARE_DNA_REPORTS)).toBe(true);

    await expect(
      harness.performAction(ACTION_KEYS.GET_SENSITIVE_CONSENTS, {}),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    await expect(
      harness.performAction(ACTION_KEYS.RECORD_SENSITIVE_CONSENT, {
        scope: "privacy-change",
        detail: "Manual note",
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    await expect(
      harness.performAction(ACTION_KEYS.UPDATE_PRIVACY_SETTINGS, {
        allowSensitiveExports: true,
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    const updatedPrivacy = await harness.performAction(ACTION_KEYS.UPDATE_PRIVACY_SETTINGS, {
      confirmSensitive: true,
      allowSensitiveExports: true,
      allowAncestryInference: false,
    }) as { policy: { allowSensitiveExports: boolean; allowAncestryInference: boolean } };
    expect(updatedPrivacy.policy.allowSensitiveExports).toBe(true);
    expect(updatedPrivacy.policy.allowAncestryInference).toBe(false);

    await harness.performAction(ACTION_KEYS.RECORD_SENSITIVE_CONSENT, {
      confirmSensitive: true,
      scope: "privacy-change",
      detail: "Manual note",
    });

    const consentsBeforePurge = await harness.performAction(ACTION_KEYS.GET_SENSITIVE_CONSENTS, {
      confirmSensitive: true,
    }) as { consents: Array<{ action: string; scope: string }> };
    expect(consentsBeforePurge.consents).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ action: ACTION_KEYS.RECORD_SENSITIVE_CONSENT, scope: "privacy-change" }),
        expect.objectContaining({ action: ACTION_KEYS.UPDATE_PRIVACY_SETTINGS, scope: "privacy-change" }),
        expect.objectContaining({ action: ACTION_KEYS.COMPARE_DNA_REPORTS, scope: "dna-access" }),
      ]),
    );

    await harness.performAction(ACTION_KEYS.PURGE_SENSITIVE_CONSENTS, {
      confirmSensitive: true,
    });

    const consentsAfterPurge = await harness.performAction(ACTION_KEYS.GET_SENSITIVE_CONSENTS, {
      confirmSensitive: true,
    }) as { consents: Array<{ action: string }> };
    expect(consentsAfterPurge.consents.some((entry) => entry.action === ACTION_KEYS.RECORD_SENSITIVE_CONSENT)).toBe(false);

    await expect(
      harness.performAction(ACTION_KEYS.DELETE_DNA_REPORT, {
        id: reportId,
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    const deleted = await harness.performAction(ACTION_KEYS.DELETE_DNA_REPORT, {
      id: reportId,
      confirmSensitive: true,
    }) as { success: boolean; dnaReport: { id: string; variants: unknown[] } };
    expect(deleted.success).toBe(true);
    expect(deleted.dnaReport.id).toBe(reportId);
    expect(deleted.dnaReport.variants).toEqual([]);

    const consentsAfterDelete = await harness.performAction(ACTION_KEYS.GET_SENSITIVE_CONSENTS, {
      confirmSensitive: true,
    }) as { consents: Array<{ action: string; scope: string }> };
    expect(consentsAfterDelete.consents).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ action: ACTION_KEYS.DELETE_DNA_REPORT, scope: "privacy-change" }),
      ]),
    );
  });

  it("creates bloodwork trends, correlation insights, and withholds biological age when coverage is too low", async () => {
    const labResult = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-04-17T09:00:00Z",
      panels: sampleBloodworkPanels,
    }) as { labResult: { id: string } };

    await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-05-17T09:00:00Z",
      panels: [
        {
          name: "Cardiometabolic",
          biomarkers: [
            { name: "LDL cholesterol", value: 118, unit: "mg/dL" },
            { name: "Ferritin", value: 55, unit: "ng/mL" },
          ],
        },
      ],
    });

    const dna = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string } };

    const trends = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_TRENDS, {}) as { trends: Array<{ biomarkerName: string; direction: string; deltaPercent?: number }> };
    expect(trends.trends.some((entry) => entry.biomarkerName.toLowerCase().includes("ldl") || entry.biomarkerName.toLowerCase().includes("ferritin"))).toBe(true);
    expect(trends.trends.some((entry) => typeof entry.deltaPercent === "number")).toBe(true);

    const correlations = await harness.performAction(ACTION_KEYS.GET_DNA_BLOODWORK_CORRELATIONS, {
      reportId: dna.dnaReport.id,
      labResultId: labResult.labResult.id,
    }) as { correlations: Array<{ title: string }> };
    expect(correlations.correlations.length).toBeGreaterThan(0);
    expect(correlations.correlations.some((entry) => /lipid|iron|vitamin/i.test(entry.title))).toBe(true);

    const sparseAge = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      labResultId: labResult.labResult.id,
      chronologicalAge: 34,
      sex: "male",
    }) as { biologicalAge: { status: string; biologicalAge: number | null } };
    expect(sparseAge.biologicalAge.status).toBe("available");

    const insufficientAge = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      chronologicalAge: 34,
      sex: "male",
      labResultId: (await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
        labName: "Sparse Panel",
        resultedAt: "2026-06-17T09:00:00Z",
        panels: [
          {
            name: "Minimal",
            biomarkers: [
              { name: "Glucose", value: 99, unit: "mg/dL" },
              { name: "Albumin", value: 4.2, unit: "g/dL" },
            ],
          },
        ],
      }) as { labResult: { id: string } }).labResult.id,
    }) as { biologicalAge: { status: string; biologicalAge: number | null; coverage: number; minimumCoverage: number } };
    expect(insufficientAge.biologicalAge.status).toBe("insufficient-data");
    expect(insufficientAge.biologicalAge.biologicalAge).toBeNull();
    expect(insufficientAge.biologicalAge.coverage).toBeLessThan(insufficientAge.biologicalAge.minimumCoverage);
  });

  it("previews and imports lab data from csv with normalization and clock metadata", async () => {
    const preview = await harness.performAction(ACTION_KEYS.PREVIEW_LAB_IMPORT, {
      fileName: "function-export.csv",
      rawData: sampleLabImportCsv,
      defaultPanelName: "Imported Labs",
    }) as {
      success: boolean;
      preview: {
        matchedRows: number;
        confidence: string;
        normalizationNotes: Array<{ message: string }>;
        panels: Array<{ name: string; biomarkers: Array<{ name: string; value: number; unit: string }> }>;
      };
    };

    expect(preview.success).toBe(true);
    expect(preview.preview.matchedRows).toBe(3);
    expect(preview.preview.confidence).toMatch(/high|medium/);
    expect(preview.preview.normalizationNotes.some((note) => note.message.includes("Converted mmol/L"))).toBe(true);
    expect(preview.preview.panels[0].biomarkers.some((entry) => entry.name === "Glucose" && entry.unit === "mg/dL")).toBe(true);

    const imported = await harness.performAction(ACTION_KEYS.IMPORT_LAB_RESULT, {
      fileName: "function-export.csv",
      rawData: sampleLabImportCsv,
      labName: "CSV Import",
      defaultPanelName: "Imported Labs",
      resultedAt: "2026-04-18T07:00:00Z",
    }) as {
      success: boolean;
      labResult: {
        id: string;
        importMetadata: { matchedRows: number; confidence: string };
        panels: Array<{ biomarkers: Array<{ name: string; referenceRangeLow?: number; referenceRangeHigh?: number; unit: string }> }>;
      };
    };

    expect(imported.success).toBe(true);
    expect(imported.labResult.importMetadata.matchedRows).toBe(3);
    expect(imported.labResult.importMetadata.confidence).toMatch(/high|medium/);
    const glucose = imported.labResult.panels.flatMap((panel) => panel.biomarkers).find((entry) => entry.name === "Glucose");
    expect(glucose?.unit).toBe("mg/dL");
    expect(glucose?.referenceRangeLow).toBeCloseTo(70.2, 1);
    expect(glucose?.referenceRangeHigh).toBeCloseTo(99, 1);

    const rejectedImport = await harness.performAction(ACTION_KEYS.IMPORT_LAB_RESULT, {
      fileName: "garbage.csv",
      rawData: "panel,name,value,unit\nUnknown,Unknown marker,12,mg/dL\n",
      labName: "Garbage Import",
    }) as { success: boolean; error?: string; preview: { matchedRows: number } };
    expect(rejectedImport.success).toBe(false);
    expect(rejectedImport.error).toContain("nothing was stored");
    expect(rejectedImport.preview.matchedRows).toBe(0);

    const clocks = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_CLOCKS, {}) as {
      clocks: Array<{ method: string; status: string }>;
    };
    expect(clocks.clocks).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ method: "kdm-style-clinical-clock", status: "available" }),
      ]),
    );
  });

  it("accepts comma-delimited 23andMe-style DNA imports", async () => {
    const preview = await harness.performAction(ACTION_KEYS.PREVIEW_DNA_IMPORT, {
      fileName: "23andme-export.csv",
      rawData: dnaSample23AndMeCsv,
    }) as { preview: { source: string; rawSnpsImported: number; snpsMatchedToKnowledgeBase: number } };

    expect(preview.preview.source).toBe("23andme");
    expect(preview.preview.rawSnpsImported).toBe(2);
    expect(preview.preview.snpsMatchedToKnowledgeBase).toBeGreaterThan(0);
  });

  it("supports vcf dna preview, duplicate detection, reanalysis, minimization, and consent history", async () => {
    const preview = await harness.performAction(ACTION_KEYS.PREVIEW_DNA_IMPORT, {
      fileName: "ola.vcf",
      rawData: dnaSampleVcf,
      privacyMode: "living",
    }) as { success: boolean; preview: { source: string; importFormat: string; genomeBuild?: string; healthInsights: unknown[] } };
    expect(preview.success).toBe(true);
    expect(preview.preview.source).toBe("vcf");
    expect(preview.preview.importFormat).toBe("vcf");
    expect(preview.preview.genomeBuild).toBe("GRCh38");
    expect(preview.preview.healthInsights.length).toBeGreaterThan(0);

    const delimitedPreview = await harness.performAction(ACTION_KEYS.PREVIEW_DNA_IMPORT, {
      fileName: "generic-dna.tsv",
      rawData: dnaSampleDelimited,
      privacyMode: "living",
    }) as { success: boolean; preview: { source: string } };
    expect(delimitedPreview.success).toBe(true);
    expect(delimitedPreview.preview.source).toBe("livedna");

    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola.vcf",
      rawData: dnaSampleVcf,
      privacyMode: "living",
    }) as { success: boolean; dnaReport: { id: string; source: string; variants: Array<unknown> } };
    expect(added.success).toBe(true);
    expect(added.dnaReport.source).toBe("vcf");
    expect(added.dnaReport.variants.length).toBeGreaterThan(0);

    const duplicate = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola.vcf",
      rawData: dnaSampleVcf,
      privacyMode: "living",
    }) as { duplicate?: boolean; dnaReport: { id: string } };
    expect(duplicate.duplicate).toBe(true);
    expect(duplicate.dnaReport.id).toBe(added.dnaReport.id);

    const kb = await harness.performAction(ACTION_KEYS.GET_DNA_KNOWLEDGE_BASE_STATUS, {}) as {
      success: boolean;
      status: { version: string; annotationCount: number; supportedSources: string[] };
    };
    expect(kb.success).toBe(true);
    expect(kb.status.version).toContain("curated");
    expect(kb.status.annotationCount).toBeGreaterThan(10);
    expect(kb.status.supportedSources).toEqual(expect.arrayContaining(["vcf", "23andme"]));

    const reanalyzed = await harness.performAction(ACTION_KEYS.REANALYZE_DNA_REPORT, {
      reportId: added.dnaReport.id,
      confirmSensitive: true,
    }) as { success: boolean; diff: { currentKnowledgeBaseVersion: string } };
    expect(reanalyzed.success).toBe(true);
    expect(reanalyzed.diff.currentKnowledgeBaseVersion).toContain("curated");

    await expect(
      harness.performAction(ACTION_KEYS.REANALYZE_DNA_REPORT, {
        reportId: added.dnaReport.id,
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    const minimized = await harness.performAction(ACTION_KEYS.MINIMIZE_DNA_REPORT, {
      reportId: added.dnaReport.id,
      confirmSensitive: true,
      reason: "Reduce retained sensitive data",
    }) as { success: boolean; dnaReport: { isPrivacyRestricted: boolean; variants: unknown[] } };
    expect(minimized.success).toBe(true);
    expect(minimized.dnaReport.isPrivacyRestricted).toBe(true);
    expect(minimized.dnaReport.variants).toEqual([]);

    await expect(
      harness.performAction(ACTION_KEYS.MINIMIZE_DNA_REPORT, {
        reportId: added.dnaReport.id,
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    const missingMinimize = await harness.performAction(ACTION_KEYS.MINIMIZE_DNA_REPORT, {
      reportId: "missing-report",
      confirmSensitive: true,
    }) as { success: boolean; dnaReport: null };
    expect(missingMinimize.success).toBe(false);
    expect(missingMinimize.dnaReport).toBeNull();

    const consents = await harness.performAction(ACTION_KEYS.GET_SENSITIVE_CONSENTS, {
      confirmSensitive: true,
    }) as {
      consents: Array<{ action: string; scope: string }>;
    };
    expect(consents.consents).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ action: ACTION_KEYS.MINIMIZE_DNA_REPORT, scope: "privacy-change" }),
        expect.objectContaining({ action: ACTION_KEYS.REANALYZE_DNA_REPORT, scope: "dna-reanalysis" }),
      ]),
    );
  });

  it("ingests wearable payloads idempotently and surfaces a richer overview", async () => {
    const syncOne = await harness.performAction(ACTION_KEYS.SYNC_WEARABLE, {
      device: "garmin",
      workouts: [
        {
          id: "garmin-1",
          wearableLogId: "garmin-1",
          name: "Tempo Run",
          type: "running",
          performedAt: "2026-04-18T06:30:00Z",
          durationMinutes: 42,
          caloriesBurned: 510,
          avgHeartRate: 154,
          distanceKm: 8.2,
        },
      ],
      sleepEntries: [
        {
          date: "2026-04-18",
          totalMinutes: 440,
          sleepScore: 82,
          deepMinutes: 88,
        },
      ],
      recoveryEntries: [
        {
          date: "2026-04-18",
          score: 71,
          overall: "yellow",
          recommendation: "Keep the next session aerobic.",
        },
      ],
    }) as { importedSessions: number };
    expect(syncOne.importedSessions).toBe(3);

    await harness.performAction(ACTION_KEYS.SYNC_WEARABLE, {
      device: "garmin",
      workouts: [
        {
          id: "garmin-1",
          wearableLogId: "garmin-1",
          name: "Tempo Run",
          type: "running",
          performedAt: "2026-04-18T06:30:00Z",
          durationMinutes: 42,
          distanceKm: 8.2,
        },
      ],
      sleepEntries: [
        {
          date: "2026-04-18",
          totalMinutes: 440,
        },
      ],
      recoveryEntries: [
        {
          date: "2026-04-18",
        },
      ],
    });

    const workoutLogs = await harness.performAction(ACTION_KEYS.GET_WORKOUT_LOGS, {
      startDate: "2026-04-18",
      endDate: "2026-04-18",
    }) as { workouts: Array<{ wearableLogId?: string; caloriesBurned?: number; avgHeartRate?: number }> };
    expect(workoutLogs.workouts.filter((entry) => entry.wearableLogId === "garmin-1")).toHaveLength(1);
    const preservedWorkout = workoutLogs.workouts.find((entry) => entry.wearableLogId === "garmin-1");
    expect(preservedWorkout?.caloriesBurned).toBe(510);
    expect(preservedWorkout?.avgHeartRate).toBe(154);

    const daySummary = await harness.performAction(ACTION_KEYS.GET_DAILY_SUMMARY, {
      date: "2026-04-18",
    }) as { sleep: { deepMinutes?: number } | null; recovery: { score: number; recommendation?: string } | null };
    expect(daySummary.sleep?.deepMinutes).toBe(88);
    expect(daySummary.recovery?.score).toBe(71);
    expect(daySummary.recovery?.recommendation).toContain("aerobic");

    const overview = await harness.getData("health.overview") as {
      workoutSummary: { totalSessions: number };
      latestBloodworkTrends: unknown[];
      pending: { nudges: unknown[] };
    };
    expect(overview.workoutSummary.totalSessions).toBe(1);
    expect(Array.isArray(overview.latestBloodworkTrends)).toBe(true);
    expect(Array.isArray(overview.pending.nudges)).toBe(true);
  });

  it("preserves ancestry opt-out during DNA reanalysis", () => {
    const report = createDnaReport({
      source: "23andme",
      privacyMode: "living",
      allowAncestryInference: false,
      retainVariantLevelData: true,
      variants: [
        {
          rsId: "rs1801133",
          chromosome: "1",
          position: 11856378,
          allele1: "T",
          allele2: "T",
          genotype: "TT",
          diploidType: "homozygousdominant",
        },
      ],
      healthInsights: [],
      rawSnpsImported: 1,
      snpsMatchedToKnowledgeBase: 0,
    });

    const { reanalyzedReport } = reanalyzeDnaReport(report);
    expect(reanalyzedReport.allowAncestryInference).toBe(false);
    expect(reanalyzedReport.ancestryComposition).toBeUndefined();
  });

  it("reanalyzes against retained genotypes even when a prior report stored no matched variants", () => {
    const legacyReport = createDnaReport({
      source: "vcf",
      privacyMode: "living",
      retainVariantLevelData: true,
      variants: [],
      retainedGenotypes: [
        {
          rsId: "rs1801133",
          chromosome: "1",
          position: 11856378,
          allele1: "T",
          allele2: "T",
          genotype: "TT",
          diploidType: "homozygousdominant",
        },
      ],
      healthInsights: [],
      rawSnpsImported: 1,
      snpsMatchedToKnowledgeBase: 0,
    });

    const { reanalyzedReport, diff } = reanalyzeDnaReport(legacyReport);
    expect(reanalyzedReport.healthInsights.length).toBeGreaterThan(0);
    expect(reanalyzedReport.variants.some((variant) => variant.rsId === "rs1801133")).toBe(true);
    expect(diff.matchedVariantDelta).toBeGreaterThan(0);
  });



  it("stores privacy-mode DNA imports without variant-level data", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme-private.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "privacy",
    }) as {
      dnaReport: {
        id: string;
        isPrivacyRestricted: boolean;
        privacyMode: string;
        variants: Array<unknown>;
        ancestryComposition?: unknown;
        fileHash?: string;
        parseWarnings: string[];
      };
      policy: { privacyMode: string; retainVariantLevelData: boolean; allowAncestryInference: boolean };
    };

    expect(added.dnaReport.isPrivacyRestricted).toBe(true);
    expect(added.dnaReport.privacyMode).toBe("privacy");
    expect(added.dnaReport.variants).toEqual([]);
    expect(added.dnaReport.ancestryComposition).toBeUndefined();
    expect(added.dnaReport.fileHash).toBeUndefined();
    expect(added.dnaReport.parseWarnings).toEqual(expect.any(Array));
    expect(added.policy.privacyMode).toBe("privacy");
    expect(added.policy.retainVariantLevelData).toBe(false);
    expect(added.policy.allowAncestryInference).toBe(false);

    const reports = await harness.performAction(ACTION_KEYS.GET_DNA_REPORTS, {}) as {
      dnaReports: Array<{
        id: string;
        variants: Array<unknown>;
        ancestryComposition?: unknown;
        fileHash?: string;
        isPrivacyRestricted?: boolean;
      }>;
    };
    const stored = reports.dnaReports.find((report) => report.id === added.dnaReport.id);

    expect(stored).toMatchObject({
      id: added.dnaReport.id,
      isPrivacyRestricted: true,
      variants: [],
      ancestryComposition: undefined,
      fileHash: undefined,
    });
  });

  it("requires explicit confirmation before including sensitive DNA export details", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string } };

    await harness.performAction(ACTION_KEYS.UPDATE_PRIVACY_SETTINGS, {
      confirmSensitive: true,
      privacyMode: "living",
      allowSensitiveExports: true,
      retainVariantLevelData: true,
      allowAncestryInference: true,
    });

    await expect(
      harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
        reportId: added.dnaReport.id,
        includeSensitive: true,
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    const privacySafe = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
      reportId: added.dnaReport.id,
    }) as { markdown: string };
    expect(privacySafe.markdown).toContain("Inferred ancestry signal: omitted in privacy-safe mode");
    expect(privacySafe.markdown).toContain("| redacted | redacted | redacted | redacted | redacted |");

    const confirmed = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
      reportId: added.dnaReport.id,
      includeSensitive: true,
      confirmSensitive: true,
    }) as { markdown: string };
    expect(confirmed.markdown).not.toContain("Inferred ancestry signal: omitted in privacy-safe mode");
    expect(confirmed.markdown).toContain("| rs1801133 |");
    expect(confirmed.markdown).toContain("Sensitive sections were included because explicit export confirmation was provided.");
  });

  it("withholds biological age when bloodwork coverage is insufficient", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Sparse Panel",
      resultedAt: "2026-04-18T09:00:00Z",
      panels: [
        {
          name: "Minimal follow-up",
          biomarkers: [
            { name: "Albumin", value: 4.3, unit: "g/dL" },
            { name: "Creatinine", value: 0.9, unit: "mg/dL" },
            { name: "Glucose", value: 92, unit: "mg/dL" },
            { name: "LDL cholesterol", value: 101, unit: "mg/dL" },
            { name: "HDL cholesterol", value: 56, unit: "mg/dL" },
          ],
        },
      ],
    }) as { labResult: { id: string } };

    const result = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      labResultId: added.labResult.id,
      chronologicalAge: 34,
      sex: "male",
    }) as {
      biologicalAge: {
        status: string;
        biologicalAge: number | null;
        ageDelta: number | null;
        confidence: string;
        coverage: number;
        minimumCoverage: number;
        notes: string[];
      };
    };

    expect(result.biologicalAge.status).toBe("insufficient-data");
    expect(result.biologicalAge.biologicalAge).toBeNull();
    expect(result.biologicalAge.ageDelta).toBeNull();
    expect(result.biologicalAge.coverage).toBeLessThan(result.biologicalAge.minimumCoverage);
    expect(result.biologicalAge.confidence).toBe("low");
    expect(result.biologicalAge.notes.some((note) => note.includes("withheld because only"))).toBe(true);
  });

  it("returns DNA and bloodwork correlations when both datasets are available", async () => {
    const dna = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string } };

    const lab = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-04-17T09:00:00Z",
      panels: sampleBloodworkPanels,
      notes: "fasted morning draw",
    }) as { labResult: { id: string } };

    const correlationResult = await harness.performAction(ACTION_KEYS.GET_DNA_BLOODWORK_CORRELATIONS, {
      reportId: dna.dnaReport.id,
      labResultId: lab.labResult.id,
    }) as {
      correlations: Array<{
        title: string;
        priority: string;
        genes: string[];
        biomarkers: string[];
        clinicianDiscussion: string[];
      }>;
    };

    expect(correlationResult.correlations.length).toBeGreaterThan(0);
    expect(correlationResult.correlations).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          title: "Cardiometabolic genetics + lipid panel",
          priority: expect.stringMatching(/high|medium/),
          genes: expect.arrayContaining(["APOE"]),
          biomarkers: expect.arrayContaining([expect.stringMatching(/lipoprotein|ldl/i)]),
          clinicianDiscussion: expect.arrayContaining([
            expect.stringContaining("family history"),
          ]),
        }),
        expect.objectContaining({
          title: "Iron-regulation genetics + ferritin",
          genes: expect.arrayContaining(["HFE"]),
          biomarkers: expect.arrayContaining([expect.stringMatching(/ferritin/i)]),
        }),
      ]),
    );
    expect(
      correlationResult.correlations.some((entry) =>
        entry.title === "Methylation / nutrient genes + supportive labs"
        && entry.genes.includes("MTHFR")
        && entry.biomarkers.some((biomarker) => /mcv|mean corpuscular volume/i.test(biomarker)),
      ),
    ).toBe(true);
  });

  it("emits ambient nudges once per day when an agent run finishes", async () => {
    await harness.performAction(ACTION_KEYS.ADD_MEDICATION, {
      name: "Vitamin D",
      dose: "1000 IU",
      frequency: "daily",
    });

    await harness.emit(
      "agent.run.finished",
      { runId: "run_1" },
      { companyId: "company_1", entityId: "run_1", entityType: "run" },
    );

    const firstCount = harness.activity.length;
    expect(firstCount).toBeGreaterThan(0);
    expect(harness.activity.some((entry) => entry.message.toLowerCase().includes("no workouts logged") || entry.message.toLowerCase().includes("dose recorded"))).toBe(true);

    await harness.emit(
      "agent.run.finished",
      { runId: "run_2" },
      { companyId: "company_1", entityId: "run_2", entityType: "run" },
    );

    expect(harness.activity.length).toBe(firstCount);
  });
});

async function buildHarness() {
  const harness = createTestHarness({ manifest });
  await plugin.definition.setup(harness.ctx);
  return harness;
}
