import { beforeEach, describe, expect, it } from "vitest";
import { createTestHarness } from "@paperclipai/plugin-sdk/testing";
import manifest from "../src/manifest.js";
import plugin from "../src/worker.js";
import { ACTION_KEYS } from "../src/constants.js";

const dnaSample23AndMe = `# This data file generated by 23andMe at: Mon Jan 15 12:34:56 2024
#
rsid\tchromosome\tposition\tgenotype
rs1801133\t1\t11856378\tTT
rs1815739\t11\t66560624\tCT
rs429358\t19\t44908684\tCT
rs4683\t22\t19963748\tAA
`;

describe("Personal Health plugin", () => {
  let harness: Awaited<ReturnType<typeof buildHarness>>;

  beforeEach(async () => {
    harness = await buildHarness();
  });

  it("exposes the expected manifest", () => {
    expect(manifest.id).toBe("personal-health");
    expect(manifest.capabilities).toContain("activity.log.write");
  });

  it("plans and summarizes workouts", async () => {
    const { workoutPlan } = await harness.performAction(ACTION_KEYS.ADD_WORKOUT_PLAN, {
      name: "Strength Base",
      type: "strength",
      phase: "build",
      targetDurationMinutes: 60,
      targetDaysPerWeek: 3,
    }) as { workoutPlan: { id: string } };

    await harness.performAction(ACTION_KEYS.LOG_WORKOUT, {
      name: "Upper body",
      type: "strength",
      durationMinutes: 65,
      rpe: 8,
      caloriesBurned: 420,
      performedAt: "2026-04-17T08:00:00Z",
    });

    const summary = await harness.performAction(ACTION_KEYS.GET_WORKOUT_SUMMARY, { days: 7 }) as { totalSessions: number; totalDurationMinutes: number };
    expect(summary.totalSessions).toBe(1);
    expect(summary.totalDurationMinutes).toBe(65);

    const plan = await harness.performAction(ACTION_KEYS.PLAN_WEEKLY_WORKOUTS, {
      availableHours: 5,
      weekStart: "2026-04-20",
      phase: "build",
    }) as { sessions: Array<{ workoutPlanId: string }> };
    expect(plan.sessions.length).toBeGreaterThan(0);
    expect(plan.sessions[0].workoutPlanId).toBe(workoutPlan.id);
  });

  it("tracks nutrition and hydration targets", async () => {
    await harness.performAction(ACTION_KEYS.SET_CALORIE_TARGET, { calories: 2400 });
    await harness.performAction(ACTION_KEYS.SET_HYDRATION_GOAL, { goalMl: 3000 });
    await harness.performAction(ACTION_KEYS.LOG_MEAL, {
      date: "2026-04-18",
      mealName: "breakfast",
      foods: [
        { name: "Greek yogurt", calories: 140, proteinGrams: 16, carbGrams: 6, fatGrams: 4 },
        { name: "Blueberries", calories: 84, proteinGrams: 1, carbGrams: 21, fatGrams: 0, fiberGrams: 4 },
      ],
    });
    await harness.performAction(ACTION_KEYS.LOG_HYDRATION, {
      date: "2026-04-18",
      amountMl: 750,
    });

    const nutrition = await harness.performAction(ACTION_KEYS.GET_NUTRITION_SUMMARY, {
      startDate: "2026-04-18",
      endDate: "2026-04-18",
    }) as { totalCalories: number; calorieTarget: number; totalMacros: { proteinGrams: number } };
    expect(nutrition.totalCalories).toBe(224);
    expect(nutrition.calorieTarget).toBe(2400);
    expect(nutrition.totalMacros.proteinGrams).toBe(17);

    const hydration = await harness.performAction(ACTION_KEYS.GET_HYDRATION, { date: "2026-04-18" }) as { totalMl: number; goalMl: number };
    expect(hydration.totalMl).toBe(750);
    expect(hydration.goalMl).toBe(3000);

    const foodDetail = await harness.performAction(ACTION_KEYS.GET_FOOD_DETAILS, { id: "food-greek-yogurt" }) as { food: { name: string } };
    expect(foodDetail.food.name).toBe("Greek yogurt");
  });

  it("parses raw DNA data into actionable reports and exports markdown", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string; healthInsights: Array<{ title: string }> } };

    expect(added.dnaReport.healthInsights.length).toBeGreaterThan(0);

    const reportId = added.dnaReport.id;
    const detail = await harness.performAction(ACTION_KEYS.GET_DNA_VARIANT_DETAIL, {
      reportId,
      rsId: "rs1801133",
    }) as { detail: { variant: { genotype: string } } };
    expect(detail.detail.variant.genotype).toBe("TT");

    const lookup = await harness.performAction(ACTION_KEYS.LOOKUP_RSID, { rsId: "rs429358" }) as { matches: Array<unknown> };
    expect(lookup.matches.length).toBe(1);

    const exported = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, { reportId }) as { markdown: string };
    expect(exported.markdown).toContain("Actionable Health Protocol");
    expect(exported.markdown).toContain("MTHFR");
  });

  it("emits ambient nudges once per day when an agent run finishes", async () => {
    await harness.performAction(ACTION_KEYS.ADD_MEDICATION, {
      name: "Vitamin D",
      dose: "1000 IU",
      frequency: "daily",
    });

    await harness.emit(
      "agent.run.finished",
      { runId: "run_1" },
      { companyId: "company_1", entityId: "run_1", entityType: "run" },
    );

    const firstCount = harness.activity.length;
    expect(firstCount).toBeGreaterThan(0);
    expect(harness.activity.some((entry) => entry.message.toLowerCase().includes("no workouts logged") || entry.message.toLowerCase().includes("dose recorded"))).toBe(true);

    await harness.emit(
      "agent.run.finished",
      { runId: "run_2" },
      { companyId: "company_1", entityId: "run_2", entityType: "run" },
    );

    expect(harness.activity.length).toBe(firstCount);
  });
});

async function buildHarness() {
  const harness = createTestHarness({ manifest });
  await plugin.definition.setup(harness.ctx);
  return harness;
}
