import { beforeEach, describe, expect, it } from "vitest";
import { createTestHarness } from "@paperclipai/plugin-sdk/testing";
import manifest from "../src/manifest.js";
import plugin from "../src/worker.js";
import { ACTION_KEYS } from "../src/constants.js";

const dnaSample23AndMe = `# This data file generated by 23andMe at: Mon Jan 15 12:34:56 2024
#
rsid\tchromosome\tposition\tgenotype
rs1801133\t1\t11856378\tTT
rs1801131\t1\t11854476\tGG
rs1805087\t1\t236885200\tGG
rs1815739\t11\t66560624\tCT
rs429358\t19\t44908684\tCT
rs4680\t22\t19963748\tAA
rs762551\t15\t75011234\tCC
rs2298383\t22\t24763011\tTT
rs4244285\t10\t94761942\tGA
rs4149056\t12\t21178615\tCC
rs2187668\t6\t32609137\tCT
rs1800562\t6\t26091179\tGA
rs17580\t14\t94844947\tAT
rs2802292\t6\t108998794\tGG
rs8176719\t9\t136132908\tDI
rs8176746\t9\t136132911\tGG
rs505922\t9\t136149229\tCT
rs713598\t7\t141673345\tCT
rs1726866\t7\t141673586\tCT
rs10246939\t7\t141673733\tCT
rs2651899\t1\t145345634\tTT
rs1006737\t12\t22804737\tAA
rs12913832\t15\t28365618\tAG
rs1805007\t16\t89986117\tCT
rs4880\t6\t160113872\tGG
rs1695\t11\t67585218\tGG
`;

const sampleBloodworkPanels = [
  {
    name: "Cardiometabolic",
    biomarkers: [
      { name: "Albumin", value: 4.1, unit: "g/dL" },
      { name: "Creatinine", value: 1.05, unit: "mg/dL" },
      { name: "Glucose", value: 102, unit: "mg/dL" },
      { name: "High-sensitivity C-reactive protein", value: 2.4, unit: "mg/L" },
      { name: "LDL cholesterol", value: 132, unit: "mg/dL" },
      { name: "HDL cholesterol", value: 43, unit: "mg/dL" },
      { name: "Total cholesterol", value: 214, unit: "mg/dL" },
      { name: "Triglycerides", value: 168, unit: "mg/dL" },
      { name: "Hemoglobin A1c", value: 5.8, unit: "%" },
    ],
  },
  {
    name: "CBC / Recovery",
    biomarkers: [
      { name: "Lymphocyte %", value: 24, unit: "%" },
      { name: "MCV", value: 92, unit: "fL" },
      { name: "RDW", value: 13.8, unit: "%" },
      { name: "Alkaline phosphatase", value: 88, unit: "U/L" },
      { name: "Blood urea nitrogen", value: 19, unit: "mg/dL" },
      { name: "Vitamin D (25-hydroxyvitamin D)", value: 26, unit: "ng/mL" },
      { name: "Magnesium", value: 1.8, unit: "mg/dL" },
      { name: "Ferritin", value: 42, unit: "ng/mL" },
      { name: "Free testosterone", value: 72, unit: "pg/mL" },
      { name: "Sex-hormone binding globulin", value: 48, unit: "nmol/L" },
    ],
  },
];

describe("Personal Health plugin", () => {
  let harness: Awaited<ReturnType<typeof buildHarness>>;

  beforeEach(async () => {
    harness = await buildHarness();
  });

  it("exposes the expected manifest", () => {
    expect(manifest.id).toBe("personal-health");
    expect(manifest.capabilities).toContain("activity.log.write");
  });

  it("plans and summarizes workouts", async () => {
    const { workoutPlan } = await harness.performAction(ACTION_KEYS.ADD_WORKOUT_PLAN, {
      name: "Strength Base",
      type: "strength",
      phase: "build",
      targetDurationMinutes: 60,
      targetDaysPerWeek: 3,
    }) as { workoutPlan: { id: string } };

    await harness.performAction(ACTION_KEYS.LOG_WORKOUT, {
      name: "Upper body",
      type: "strength",
      durationMinutes: 65,
      rpe: 8,
      caloriesBurned: 420,
      performedAt: "2026-04-17T08:00:00Z",
    });

    const summary = await harness.performAction(ACTION_KEYS.GET_WORKOUT_SUMMARY, { days: 7 }) as { totalSessions: number; totalDurationMinutes: number };
    expect(summary.totalSessions).toBe(1);
    expect(summary.totalDurationMinutes).toBe(65);

    const plan = await harness.performAction(ACTION_KEYS.PLAN_WEEKLY_WORKOUTS, {
      availableHours: 5,
      weekStart: "2026-04-20",
      phase: "build",
    }) as { sessions: Array<{ workoutPlanId: string }> };
    expect(plan.sessions.length).toBeGreaterThan(0);
    expect(plan.sessions[0].workoutPlanId).toBe(workoutPlan.id);
  });

  it("tracks nutrition and hydration targets", async () => {
    await harness.performAction(ACTION_KEYS.SET_CALORIE_TARGET, { calories: 2400 });
    await harness.performAction(ACTION_KEYS.SET_HYDRATION_GOAL, { goalMl: 3000 });
    await harness.performAction(ACTION_KEYS.LOG_MEAL, {
      date: "2026-04-18",
      mealName: "breakfast",
      foods: [
        { name: "Greek yogurt", calories: 140, proteinGrams: 16, carbGrams: 6, fatGrams: 4 },
        { name: "Blueberries", calories: 84, proteinGrams: 1, carbGrams: 21, fatGrams: 0, fiberGrams: 4 },
      ],
    });
    await harness.performAction(ACTION_KEYS.LOG_HYDRATION, {
      date: "2026-04-18",
      amountMl: 750,
    });

    const nutrition = await harness.performAction(ACTION_KEYS.GET_NUTRITION_SUMMARY, {
      startDate: "2026-04-18",
      endDate: "2026-04-18",
    }) as { totalCalories: number; calorieTarget: number; totalMacros: { proteinGrams: number } };
    expect(nutrition.totalCalories).toBe(224);
    expect(nutrition.calorieTarget).toBe(2400);
    expect(nutrition.totalMacros.proteinGrams).toBe(17);

    const hydration = await harness.performAction(ACTION_KEYS.GET_HYDRATION, { date: "2026-04-18" }) as { totalMl: number; goalMl: number };
    expect(hydration.totalMl).toBe(750);
    expect(hydration.goalMl).toBe(3000);

    const foodDetail = await harness.performAction(ACTION_KEYS.GET_FOOD_DETAILS, { id: "food-greek-yogurt" }) as { food: { name: string } };
    expect(foodDetail.food.name).toBe("Greek yogurt");
  });

  it("parses raw DNA data into actionable reports and exports markdown", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string; healthInsights: Array<{ title: string }> } };

    expect(added.dnaReport.healthInsights.length).toBeGreaterThan(0);

    const reportId = added.dnaReport.id;
    const detail = await harness.performAction(ACTION_KEYS.GET_DNA_VARIANT_DETAIL, {
      reportId,
      rsId: "rs1801133",
    }) as { detail: { variant: { genotype: string } } };
    expect(detail.detail.variant.genotype).toBe("TT");

    const lookup = await harness.performAction(ACTION_KEYS.LOOKUP_RSID, { rsId: "rs429358" }) as { matches: Array<unknown> };
    expect(lookup.matches.length).toBe(1);

    const exported = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, { reportId }) as { markdown: string };
    expect(exported.markdown).toContain("Actionable Health Protocol");
    expect(exported.markdown).toContain("MTHFR");
    expect(exported.markdown).toContain("Disease Risk Watchlist");
    expect(exported.markdown).toContain("Pharmacogenomic Watch-outs");
    expect(exported.markdown).toContain("Trait Snapshots");
    expect(exported.markdown).toContain("Carrier / Protective Notes");

    const priority = await harness.performAction(ACTION_KEYS.GET_DNA_PRIORITY_FINDINGS, { reportId }) as { priorityFindings: Array<{ title: string }> };
    expect(priority.priorityFindings[0].title.length).toBeGreaterThan(0);

    const diseaseRisks = await harness.performAction(ACTION_KEYS.GET_DNA_DISEASE_RISKS, { reportId }) as { diseaseRisks: Array<{ domain: string }> };
    expect(diseaseRisks.diseaseRisks.length).toBeGreaterThan(0);

    const pharmacogenomics = await harness.performAction(ACTION_KEYS.GET_DNA_PHARMACOGENOMICS, { reportId }) as { pharmacogenomics: Array<{ gene: string }> };
    expect(pharmacogenomics.pharmacogenomics.length).toBeGreaterThan(0);

    const pathways = await harness.performAction(ACTION_KEYS.GET_DNA_PATHWAYS, { reportId }) as { pathways: Array<{ pathway: string }> };
    expect(pathways.pathways.length).toBeGreaterThan(0);

    const traits = await harness.performAction(ACTION_KEYS.GET_DNA_TRAITS, { reportId }) as { traits: Array<{ title: string }> };
    expect(traits.traits.length).toBeGreaterThan(0);
    expect(traits.traits.some((entry) => entry.title.includes("Blood Type") || entry.title.includes("Caffeine") || entry.title.includes("Training"))).toBe(true);

    const carrierStatus = await harness.performAction(ACTION_KEYS.GET_DNA_CARRIER_STATUS, { reportId }) as { carrierStatus: Array<{ gene: string }> };
    expect(carrierStatus.carrierStatus.some((entry) => entry.gene === "HFE" || entry.gene === "SERPINA1")).toBe(true);

    const protective = await harness.performAction(ACTION_KEYS.GET_DNA_PROTECTIVE_VARIANTS, { reportId }) as { protectiveVariants: Array<{ gene: string }> };
    expect(protective.protectiveVariants.some((entry) => entry.gene === "FOXO3" || entry.gene === "APOE")).toBe(true);

    const monitoring = await harness.performAction(ACTION_KEYS.GET_DNA_MONITORING_PLAN, { reportId }) as { monitoringPlan: Array<{ focus: string }> };
    expect(monitoring.monitoringPlan.length).toBeGreaterThan(0);

    const supplements = await harness.performAction(ACTION_KEYS.GET_DNA_SUPPLEMENT_RECOMMENDATIONS, { reportId }) as { supplementRecommendations: Array<{ supplement: string }> };
    expect(supplements.supplementRecommendations.some((entry) => entry.supplement.toLowerCase().includes("methylfolate") || entry.supplement.toLowerCase().includes("vitamin"))).toBe(true);

    const comprehensive = await harness.performAction(ACTION_KEYS.EXPORT_DNA_COMPREHENSIVE_REPORT, { reportId }) as { markdown: string };
    expect(comprehensive.markdown).toContain("Comprehensive Genetics Report");
    expect(comprehensive.markdown).toContain("Trait Summaries");
    expect(comprehensive.markdown).toContain("Carrier Status");
    expect(comprehensive.markdown).toContain("Supplement Considerations");
  });

  it("analyzes bloodwork against BloodWork-inspired biomarker logic and biological age", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-04-17T09:00:00Z",
      panels: sampleBloodworkPanels,
      notes: "fasted morning draw",
    }) as { labResult: { id: string } };

    const biomarkerLookup = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_BIOMARKER, {
      query: "vitamin d",
    }) as { biomarker: { id: string; category: string } };
    expect(biomarkerLookup.biomarker.id).toBe("vitamin-d");
    expect(biomarkerLookup.biomarker.category).toBe("Hormone Balance");

    const analysis = await harness.performAction(ACTION_KEYS.ANALYZE_BLOODWORK, {
      labResultId: added.labResult.id,
      age: 34,
      chronologicalAge: 34,
      sex: "male",
    }) as { success: boolean; analysis: { evaluatedBiomarkers: Array<{ status: string }>; overallSummary: string; coverageSummary: string } };
    expect(analysis.success).toBe(true);
    expect(analysis.analysis.evaluatedBiomarkers.length).toBeGreaterThan(8);
    expect(analysis.analysis.overallSummary).toContain("Strongest category");
    expect(analysis.analysis.coverageSummary).toContain("coverage");

    const categoryScores = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_CATEGORY_SCORES, {
      labResultId: added.labResult.id,
      age: 34,
      sex: "male",
    }) as { categoryScores: Array<{ category: string; score: number }> };
    expect(categoryScores.categoryScores.some((entry) => entry.category === "Heart Health")).toBe(true);

    const biologicalAge = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      labResultId: added.labResult.id,
      chronologicalAge: 34,
      sex: "male",
    }) as { biologicalAge: { method: string; status: string; comboSignals: Array<{ name: string }> } };
    expect(biologicalAge.biologicalAge.method).toBe("kdm-style-clinical-clock");
    expect(biologicalAge.biologicalAge.status).toBe("available");
    expect(biologicalAge.biologicalAge.comboSignals.some((entry) => entry.name === "Metabolic Combo")).toBe(true);

    const actionPlan = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_ACTION_PLAN, {
      labResultId: added.labResult.id,
      age: 34,
      sex: "male",
    }) as { actionPlan: Array<{ biomarkerName: string }> };
    expect(actionPlan.actionPlan.length).toBeGreaterThan(0);
  });

  it("enforces privacy mode, confirmation gates, and audit logging for DNA", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "private-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "privacy",
    }) as { dnaReport: { id: string; isPrivacyRestricted: boolean; variants: unknown[]; ancestryComposition?: unknown } };

    expect(added.dnaReport.isPrivacyRestricted).toBe(true);
    expect(added.dnaReport.variants).toHaveLength(0);
    expect(added.dnaReport.ancestryComposition).toBeUndefined();

    const reportId = added.dnaReport.id;
    const variants = await harness.performAction(ACTION_KEYS.GET_DNA_VARIANTS, { reportId }) as { dnaVariants: unknown[]; error?: string };
    expect(variants.dnaVariants).toHaveLength(0);
    expect(variants.error).toContain("explicit confirmation");

    const exportAttempt = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
      reportId,
      includeSensitive: true,
      confirmSensitive: true,
    }) as { error?: string; markdown: string };
    expect(exportAttempt.error).toContain("Sensitive export disabled");

    const privacyStatus = await harness.performAction(ACTION_KEYS.GET_PRIVACY_STATUS, {}) as { summary: string };
    expect(privacyStatus.summary.toLowerCase()).toContain("privacy mode");

    const auditLog = await harness.performAction(ACTION_KEYS.GET_HEALTH_AUDIT_LOG, {
      confirmSensitive: true,
    }) as { auditLog: Array<{ action: string }> };
    expect(auditLog.auditLog.some((entry) => entry.action === ACTION_KEYS.ADD_DNA_REPORT)).toBe(true);
  });

  it("creates bloodwork trends, correlation insights, and withholds biological age when coverage is too low", async () => {
    const labResult = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-04-17T09:00:00Z",
      panels: sampleBloodworkPanels,
    }) as { labResult: { id: string } };

    await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-05-17T09:00:00Z",
      panels: [
        {
          name: "Cardiometabolic",
          biomarkers: [
            { name: "LDL cholesterol", value: 118, unit: "mg/dL" },
            { name: "Ferritin", value: 55, unit: "ng/mL" },
          ],
        },
      ],
    });

    const dna = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string } };

    const trends = await harness.performAction(ACTION_KEYS.GET_BLOODWORK_TRENDS, {}) as { trends: Array<{ biomarkerName: string; direction: string }> };
    expect(trends.trends.some((entry) => entry.biomarkerName.toLowerCase().includes("ldl") || entry.biomarkerName.toLowerCase().includes("ferritin"))).toBe(true);

    const correlations = await harness.performAction(ACTION_KEYS.GET_DNA_BLOODWORK_CORRELATIONS, {
      reportId: dna.dnaReport.id,
      labResultId: labResult.labResult.id,
    }) as { correlations: Array<{ title: string }> };
    expect(correlations.correlations.length).toBeGreaterThan(0);
    expect(correlations.correlations.some((entry) => /lipid|iron|vitamin/i.test(entry.title))).toBe(true);

    const sparseAge = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      labResultId: labResult.labResult.id,
      chronologicalAge: 34,
      sex: "male",
    }) as { biologicalAge: { status: string; biologicalAge: number | null } };
    expect(sparseAge.biologicalAge.status).toBe("available");

    const insufficientAge = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      chronologicalAge: 34,
      sex: "male",
      labResultId: (await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
        labName: "Sparse Panel",
        resultedAt: "2026-06-17T09:00:00Z",
        panels: [
          {
            name: "Minimal",
            biomarkers: [
              { name: "Glucose", value: 99, unit: "mg/dL" },
              { name: "Albumin", value: 4.2, unit: "g/dL" },
            ],
          },
        ],
      }) as { labResult: { id: string } }).labResult.id,
    }) as { biologicalAge: { status: string; biologicalAge: number | null; coverage: number; minimumCoverage: number } };
    expect(insufficientAge.biologicalAge.status).toBe("insufficient-data");
    expect(insufficientAge.biologicalAge.biologicalAge).toBeNull();
    expect(insufficientAge.biologicalAge.coverage).toBeLessThan(insufficientAge.biologicalAge.minimumCoverage);
  });



  it("stores privacy-mode DNA imports without variant-level data", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme-private.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "privacy",
    }) as {
      dnaReport: {
        id: string;
        isPrivacyRestricted: boolean;
        privacyMode: string;
        variants: Array<unknown>;
        ancestryComposition?: unknown;
        fileHash?: string;
        parseWarnings: string[];
      };
      policy: { privacyMode: string; retainVariantLevelData: boolean; allowAncestryInference: boolean };
    };

    expect(added.dnaReport.isPrivacyRestricted).toBe(true);
    expect(added.dnaReport.privacyMode).toBe("privacy");
    expect(added.dnaReport.variants).toEqual([]);
    expect(added.dnaReport.ancestryComposition).toBeUndefined();
    expect(added.dnaReport.fileHash).toBeUndefined();
    expect(added.dnaReport.parseWarnings).toEqual(expect.any(Array));
    expect(added.policy.privacyMode).toBe("privacy");
    expect(added.policy.retainVariantLevelData).toBe(false);
    expect(added.policy.allowAncestryInference).toBe(false);

    const reports = await harness.performAction(ACTION_KEYS.GET_DNA_REPORTS, {}) as {
      dnaReports: Array<{
        id: string;
        variants: Array<unknown>;
        ancestryComposition?: unknown;
        fileHash?: string;
        isPrivacyRestricted?: boolean;
      }>;
    };
    const stored = reports.dnaReports.find((report) => report.id === added.dnaReport.id);

    expect(stored).toMatchObject({
      id: added.dnaReport.id,
      isPrivacyRestricted: true,
      variants: [],
      ancestryComposition: undefined,
      fileHash: undefined,
    });
  });

  it("requires explicit confirmation before including sensitive DNA export details", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string } };

    await harness.performAction(ACTION_KEYS.UPDATE_PRIVACY_SETTINGS, {
      privacyMode: "living",
      allowSensitiveExports: true,
      retainVariantLevelData: true,
      allowAncestryInference: true,
    });

    await expect(
      harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
        reportId: added.dnaReport.id,
        includeSensitive: true,
      }),
    ).rejects.toThrow("confirmSensitive must be true for this sensitive operation.");

    const privacySafe = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
      reportId: added.dnaReport.id,
    }) as { markdown: string };
    expect(privacySafe.markdown).toContain("Inferred ancestry signal: omitted in privacy-safe mode");
    expect(privacySafe.markdown).toContain("| redacted | redacted | redacted | redacted | redacted |");

    const confirmed = await harness.performAction(ACTION_KEYS.EXPORT_DNA_INSIGHTS, {
      reportId: added.dnaReport.id,
      includeSensitive: true,
      confirmSensitive: true,
    }) as { markdown: string };
    expect(confirmed.markdown).not.toContain("Inferred ancestry signal: omitted in privacy-safe mode");
    expect(confirmed.markdown).toContain("| rs1801133 |");
    expect(confirmed.markdown).toContain("Sensitive sections were included because explicit export confirmation was provided.");
  });

  it("withholds biological age when bloodwork coverage is insufficient", async () => {
    const added = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Sparse Panel",
      resultedAt: "2026-04-18T09:00:00Z",
      panels: [
        {
          name: "Minimal follow-up",
          biomarkers: [
            { name: "Albumin", value: 4.3, unit: "g/dL" },
            { name: "Creatinine", value: 0.9, unit: "mg/dL" },
            { name: "Glucose", value: 92, unit: "mg/dL" },
            { name: "LDL cholesterol", value: 101, unit: "mg/dL" },
            { name: "HDL cholesterol", value: 56, unit: "mg/dL" },
          ],
        },
      ],
    }) as { labResult: { id: string } };

    const result = await harness.performAction(ACTION_KEYS.CALCULATE_BIOLOGICAL_AGE, {
      labResultId: added.labResult.id,
      chronologicalAge: 34,
      sex: "male",
    }) as {
      biologicalAge: {
        status: string;
        biologicalAge: number | null;
        ageDelta: number | null;
        confidence: string;
        coverage: number;
        minimumCoverage: number;
        notes: string[];
      };
    };

    expect(result.biologicalAge.status).toBe("insufficient-data");
    expect(result.biologicalAge.biologicalAge).toBeNull();
    expect(result.biologicalAge.ageDelta).toBeNull();
    expect(result.biologicalAge.coverage).toBeLessThan(result.biologicalAge.minimumCoverage);
    expect(result.biologicalAge.confidence).toBe("low");
    expect(result.biologicalAge.notes.some((note) => note.includes("withheld because only"))).toBe(true);
  });

  it("returns DNA and bloodwork correlations when both datasets are available", async () => {
    const dna = await harness.performAction(ACTION_KEYS.ADD_DNA_REPORT, {
      fileName: "ola-23andme.txt",
      rawData: dnaSample23AndMe,
      privacyMode: "living",
    }) as { dnaReport: { id: string } };

    const lab = await harness.performAction(ACTION_KEYS.ADD_LAB_RESULT, {
      labName: "Function Health",
      resultedAt: "2026-04-17T09:00:00Z",
      panels: sampleBloodworkPanels,
      notes: "fasted morning draw",
    }) as { labResult: { id: string } };

    const correlationResult = await harness.performAction(ACTION_KEYS.GET_DNA_BLOODWORK_CORRELATIONS, {
      reportId: dna.dnaReport.id,
      labResultId: lab.labResult.id,
    }) as {
      correlations: Array<{
        title: string;
        priority: string;
        genes: string[];
        biomarkers: string[];
        clinicianDiscussion: string[];
      }>;
    };

    expect(correlationResult.correlations.length).toBeGreaterThan(0);
    expect(correlationResult.correlations).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          title: "Cardiometabolic genetics + lipid panel",
          priority: expect.stringMatching(/high|medium/),
          genes: expect.arrayContaining(["APOE"]),
          biomarkers: expect.arrayContaining([expect.stringMatching(/lipoprotein|ldl/i)]),
          clinicianDiscussion: expect.arrayContaining([
            expect.stringContaining("family history"),
          ]),
        }),
        expect.objectContaining({
          title: "Iron-regulation genetics + ferritin",
          genes: expect.arrayContaining(["HFE"]),
          biomarkers: expect.arrayContaining([expect.stringMatching(/ferritin/i)]),
        }),
      ]),
    );
    expect(
      correlationResult.correlations.some((entry) =>
        entry.title === "Methylation / nutrient genes + supportive labs"
        && entry.genes.includes("MTHFR")
        && entry.biomarkers.some((biomarker) => /mcv|mean corpuscular volume/i.test(biomarker)),
      ),
    ).toBe(true);
  });

  it("emits ambient nudges once per day when an agent run finishes", async () => {
    await harness.performAction(ACTION_KEYS.ADD_MEDICATION, {
      name: "Vitamin D",
      dose: "1000 IU",
      frequency: "daily",
    });

    await harness.emit(
      "agent.run.finished",
      { runId: "run_1" },
      { companyId: "company_1", entityId: "run_1", entityType: "run" },
    );

    const firstCount = harness.activity.length;
    expect(firstCount).toBeGreaterThan(0);
    expect(harness.activity.some((entry) => entry.message.toLowerCase().includes("no workouts logged") || entry.message.toLowerCase().includes("dose recorded"))).toBe(true);

    await harness.emit(
      "agent.run.finished",
      { runId: "run_2" },
      { companyId: "company_1", entityId: "run_2", entityType: "run" },
    );

    expect(harness.activity.length).toBe(firstCount);
  });
});

async function buildHarness() {
  const harness = createTestHarness({ manifest });
  await plugin.definition.setup(harness.ctx);
  return harness;
}
